// JavaScript/hangman-react/src/components/WordInput.js
import React, { useContext } from 'react';
import { Context } from '../context';
import randomWords from 'random-words';

const WordInput = () => {
  const [state, setState] = useContext(Context);
  const { selectedWord, correctLetters } = state;

  const changeWord = () => {
    setState({
      selectedWord: randomWords(),
      wrongLetters: [],
      correctLetters: [],
      playable: true,
      msg: null,
    });
  };

  if (selectedWord) {
    return (
      <>
        <h3>Enter The Hidden Word</h3>
        <div className="d-flex justify-content-center">
          {selectedWord.split('').map((letter, i) => {
            return (
              <span key={i} className="letter">
                {correctLetters.includes(letter) ? letter : ''}
              </span>
            );
          })}
        </div>
        <button className="btn btn-secondary my-3" onClick={changeWord}>
          Change The Word
        </button>
      </>
    );
  } else {
    return (
      <>
        <h3>Enter The Hidden Word</h3>
        <h6>Hidden word is loading...</h6>
      </>
    );
  }
};

export default WordInput;

// JavaScript/hangman-angular/src/app/components/game/word-input/word-input.component.ts
import { Component, OnInit } from '@angular/core';
import { StoreService } from '../../../store.service';

@Component({
  selector: 'app-word-input',
  templateUrl: './word-input.component.html',
  styleUrls: ['./word-input.component.css'],
})
export class WordInputComponent implements OnInit {
  constructor(public store: StoreService) {}

  ngOnInit(): void {}

  changeWord(): void {
    this.store.resetTheWord();
  }
}

<div>
  <h3>Guess The Hidden Word</h3>

  <div *ngIf="store.selectedWord.length === 0">
    <p class="lead">Loading the hidden word</p>
  </div>

  <div class="d-flex justify-content-center">
    <div *ngFor="let letter of store.selectedWord.split('')">
      <div
        *ngIf="
          store.correctLetters.includes(letter);
          then thenBlock;
          else elseBlock
        "
      ></div>
      <ng-template #thenBlock>
        <span class="letter">{{ letter }}</span>
      </ng-template>
      <ng-template #elseBlock>
        <span class="letter">{{ " " }}</span>
      </ng-template>
    </div>
  </div>
  <button class="btn btn-secondary my-3" (click)="changeWord()">
    Change The Word
  </button>
</div>
