// JavaScript/hangman-angular/src/app/components/game/figure/figure.component.ts
import { Component, OnInit } from '@angular/core';
import { StoreService } from 'src/app/store.service';

@Component({
  selector: 'app-figure',
  templateUrl: './figure.component.html',
  styleUrls: ['./figure.component.css'],
})
export class FigureComponent implements OnInit {
  constructor(public store: StoreService) {}

  ngOnInit(): void {}
}

<div class="figure-container">
  <svg height="250" width="200" className="figure-container">
    <!-- Rod -->
    <line x1="60" y1="20" x2="140" y2="20" />
    <line x1="140" y1="20" x2="140" y2="50" />
    <line x1="60" y1="20" x2="60" y2="230" />
    <line x1="20" y1="230" x2="100" y2="230" />

    <!-- Head -->
    <circle *ngIf="store.wrongLetters.length > 0" cx="140" cy="70" r="20" />

    <!-- Body -->
    <line
      *ngIf="store.wrongLetters.length > 1"
      x1="140"
      y1="90"
      x2="140"
      y2="150"
    />

    <!-- Arms -->
    <line
      *ngIf="store.wrongLetters.length > 2"
      x1="140"
      y1="120"
      x2="120"
      y2="100"
    />
    <line
      *ngIf="store.wrongLetters.length > 3"
      x1="140"
      y1="120"
      x2="160"
      y2="100"
    />

    <!-- Legs -->
    <line
      *ngIf="store.wrongLetters.length > 4"
      x1="140"
      y1="150"
      x2="120"
      y2="180"
    />
    <line
      *ngIf="store.wrongLetters.length > 5"
      x1="140"
      y1="150"
      x2="160"
      y2="180"
    />
  </svg>
</div>

// JavaScript/hangman-react/src/components/Figure.js
import React, { useContext } from 'react';
import { Context } from '../context';

const Figure = () => {
  const [state] = useContext(Context);
  const { wrongLetters } = state;

  return (
    <svg height="250" width="200" className="figure-container">
      {/* Rod */}
      <line x1="60" y1="20" x2="140" y2="20" />
      <line x1="140" y1="20" x2="140" y2="50" />
      <line x1="60" y1="20" x2="60" y2="230" />
      <line x1="20" y1="230" x2="100" y2="230" />

      {/* Head */}
      {wrongLetters.length > 0 && <circle cx="140" cy="70" r="20" />}

      {/* Body */}
      {wrongLetters.length > 1 && <line x1="140" y1="90" x2="140" y2="150" />}

      {/* Arms */}
      {wrongLetters.length > 2 && <line x1="140" y1="120" x2="120" y2="100" />}
      {wrongLetters.length > 3 && <line x1="140" y1="120" x2="160" y2="100" />}

      {/* Legs */}
      {wrongLetters.length > 4 && <line x1="140" y1="150" x2="120" y2="180" />}
      {wrongLetters.length > 5 && <line x1="140" y1="150" x2="160" y2="180" />}
    </svg>
  );
};

export default Figure;
