// JavaScript/hangman-vuejs/src/components/WrongLetters.vue
<template>
  <div>
    <h3>Wrong Letters</h3>
    <div class="d-flex justify-content-center">
      <p v-if="wrongLetters.length === 0">No Wrong Letter</p>

      <div v-for="(letter, i) in wrongLetters" :key="i">
        <span class="letter">{{ letter }}</span>
      </div>
    </div>
  </div>
</template>

<script>
import { mapGetters } from 'vuex';

export default {
  name: 'WrongLetters',

  computed: {
    ...mapGetters({ wrongLetters: 'getWrongLetters' }),
  },
};
</script>

<style></style>

// JavaScript/hangman-react/src/components/WrongLetters.js
import React, { useContext } from 'react';
import { Context } from '../context';

const WrongLetters = () => {
  const [state] = useContext(Context);
  const { wrongLetters } = state;

  return (
    <>
      <h3>Wrong Letters</h3>
      <div className="d-flex justify-content-center">
        {wrongLetters.length === 0 && <p>No Wrong Letter</p>}
        {wrongLetters.map((letter) => (
          <h6 key={letter} className="letter">
            {letter}
          </h6>
        ))}
      </div>
    </>
  );
};

export default WrongLetters;
