// JavaScript/hangman-angular/src/app/components/game/wrong-letters/wrong-letters.component.ts
import { Component, OnInit } from '@angular/core';
import { StoreService } from '../../../store.service';

@Component({
  selector: 'app-wrong-letters',
  templateUrl: './wrong-letters.component.html',
  styleUrls: ['./wrong-letters.component.css'],
})
export class WrongLettersComponent implements OnInit {
  constructor(public store: StoreService) {}

  ngOnInit(): void {}
}

<div>
  <h3>Wrong Letters</h3>

  <div *ngIf="store.wrongLetters.length === 0">
    <p class="lead">No Wrong Letter</p>
  </div>

  <div class="d-flex justify-content-center">
    <div *ngFor="let letter of store.wrongLetters">
      <h6 class="letter">{{ letter }}</h6>
    </div>
  </div>
</div>

// JavaScript/hangman-react/src/components/WrongLetters.js
import React, { useContext } from 'react';
import { Context } from '../context';

const WrongLetters = () => {
  const [state] = useContext(Context);
  const { wrongLetters } = state;

  return (
    <>
      <h3>Wrong Letters</h3>
      <div className="d-flex justify-content-center">
        {wrongLetters.length === 0 && <p>No Wrong Letter</p>}
        {wrongLetters.map((letter) => (
          <h6 className="letter">{letter}</h6>
        ))}
      </div>
    </>
  );
};

export default WrongLetters;
