// JavaScript/hangman-vuejs/src/components/EndGameModal.vue
<template>
  <div>
    <button
      type="button"
      class="d-none"
      data-toggle="modal"
      data-target="#endGameModal"
      id="endGameModalBtn"
    ></button>

    <div
      class="modal fade"
      id="endGameModal"
      tabindex="-1"
      role="dialog"
      aria-labelledby="exampleModalCenterTitle"
      aria-hidden="true"
    >
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLongTitle">
              Game Over
            </h5>
            <button
              type="button"
              class="close"
              data-dismiss="modal"
              aria-label="Close"
            >
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">{{ msg }}</div>
          <div class="modal-footer">
            <button
              type="button"
              class="btn btn-dark"
              @click="restartGame"
              data-dismiss="modal"
            >
              Play Again
            </button>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import { mapGetters, mapActions } from 'vuex';
export default {
  name: 'EndGameModal',

  watch: {
    playable(newValue, oldValue) {
      if (newValue !== oldValue) {
        document.getElementById('endGameModalBtn').click();
      }
    },
  },

  methods: {
    ...mapActions(['resetState']),
    restartGame() {
      this.resetState();
    },
  },

  computed: {
    ...mapGetters({ msg: 'getMsg', playable: 'getPlayable' }),
  },
};
</script>
<style></style>

// JavaScript/hangman-angular/src/app/components/game/end-game-modal/end-game-modal.component.ts
import { Component, OnInit } from '@angular/core';

import { StoreService } from '../../../store.service';

@Component({
  selector: 'app-end-game-modal',
  templateUrl: './end-game-modal.component.html',
  styleUrls: ['./end-game-modal.component.css'],
})
export class EndGameModalComponent implements OnInit {
  constructor(public store: StoreService) {}

  public restartGame() {
    this.store.resetTheWord();
  }

  ngOnInit(): void {}
}

<div>
  <button
    type="button"
    class="d-none"
    data-toggle="modal"
    data-target="#endGameModal"
    id="endGameModalBtn"
  ></button>

  <div
    class="modal fade"
    id="endGameModal"
    tabindex="-1"
    role="dialog"
    aria-labelledby="exampleModalCenterTitle"
    aria-hidden="true"
  >
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLongTitle">
            Game Over
          </h5>
          <button
            type="button"
            class="close"
            data-dismiss="modal"
            aria-label="Close"
          >
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">{{ store.msg }}</div>
        <div class="modal-footer">
          <button
            type="button"
            class="btn btn-dark"
            data-dismiss="modal"
            (click)="restartGame()"
          >
            Play Again
          </button>
        </div>
      </div>
    </div>
  </div>
</div>
