// JavaScript/hangman-react-native/components/Figure.js
import React, {useContext} from 'react';
import {Context} from '../globalState';
import {Svg, Line, Circle, Rect, G} from 'react-native-svg';

const Figure = () => {
  const [state] = useContext(Context);
  const {wrongLetters} = state;

  return (
    <Svg
      height="200"
      width="200"
      viewBox="-20 0 200 450"
      preserveAspectRatio="xMinYMin meet"
      fill="white"
      stroke="#f1f1f1"
      color="white">
      {/* Rod */}
      <Rect fill="white" width="10" height="400" x="20" y="0" />
      <Rect fill="white" width="300" height="10" x="20" y="0" />
      <Rect fill="white" width="150" height="10" x="0" y="400" />
      <Line
        x1="250"
        y1="0"
        x2="250"
        y2="120"
        stroke="#f1f1f1"
        strokeWidth="5"
      />

      {/* Head */}
      {wrongLetters.length > 0 && (
        <Circle cx="250" cy="150" r="30" fill="#f1f1f1" />
      )}

      {/* Body */}
      {wrongLetters.length > 1 && (
        <Rect width="10" height="100" x="245" y="150" i fill="#f1f1f1" />
      )}

      {/* Arms */}
      <G>
        {wrongLetters.length > 2 && (
          <Line
            x1="250"
            y1="200"
            x2="220"
            y2="230"
            stroke="#f1f1f1"
            stroke-Linecap="round"
            strokeWidth="10"
          />
        )}
        {wrongLetters.length > 3 && (
          <Line
            x1="250"
            y1="200"
            x2="280"
            y2="230"
            stroke="#f1f1f1"
            stroke-Linecap="round"
            strokeWidth="10"
          />
        )}
      </G>

      {/* Legs */}
      <G>
        {wrongLetters.length > 4 && (
          <Line
            x1="250"
            y1="250"
            x2="230"
            y2="300"
            stroke="#f1f1f1"
            stroke-Linecap="round"
            strokeWidth="10"
          />
        )}
        {wrongLetters.length > 5 && (
          <Line
            x1="250"
            y1="250"
            x2="270"
            y2="300"
            stroke="#f1f1f1"
            stroke-Linecap="round"
            strokeWidth="10"
          />
        )}
      </G>
    </Svg>
  );
};

export default Figure;

// JavaScript/hangman-vuejs/src/components/Figure.vue
<template>
  <svg height="250" width="200" class="figure-container">
    <!-- Rod -->
    <line x1="60" y1="20" x2="140" y2="20" />
    <line x1="140" y1="20" x2="140" y2="50" />
    <line x1="60" y1="20" x2="60" y2="230" />
    <line x1="20" y1="230" x2="100" y2="230" />

    <!-- Head -->
    <circle v-if="wrongLetters.length > 0" cx="140" cy="70" r="20" />

    <!-- Body -->
    <line v-if="wrongLetters.length > 1" x1="140" y1="90" x2="140" y2="150" />

    <!-- Arms -->
    <line v-if="wrongLetters.length > 2" x1="140" y1="120" x2="120" y2="100" />
    <line v-if="wrongLetters.length > 3" x1="140" y1="120" x2="160" y2="100" />

    <!-- Legs -->
    <line v-if="wrongLetters.length > 4" x1="140" y1="150" x2="120" y2="180" />
    <line v-if="wrongLetters.length > 5" x1="140" y1="150" x2="160" y2="180" />
  </svg>
</template>

<script>
import { mapGetters } from 'vuex';

export default {
  name: 'Figure',

  computed: {
    ...mapGetters({ wrongLetters: 'getWrongLetters' }),
  },
};
</script>

<style scoped>
.figure-container {
  fill: transparent;
  stroke: #fff;
  stroke-width: 4px;
  stroke-linecap: round;
}
</style>
