// JavaScript/hangman-react/src/components/Index.js
import React, { useEffect, useContext } from 'react';

import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

// Components
import WordInput from './WordInput';
import Figure from './Figure';
import WrongLetters from './WrongLetters';
import EndGameModal from './EndGameModal';
import { checkWin } from './helpers/helpers';
import { Context } from '../context';

toast.configure();
const Index = () => {
  const [state, setState] = useContext(Context);
  const { correctLetters, wrongLetters, selectedWord, playable, msg } = state;

  const sendNotification = (msg) => {
    toast(msg, {
      position: 'bottom-center',
      autoClose: 2000,
      hideProgressBar: false,
      closeOnClick: true,
      pauseOnHover: false,
      draggable: true,
      progress: undefined,
    });
  };

  useEffect(() => {
    if (selectedWord) {
      const checkWinStatus = checkWin(
        correctLetters,
        wrongLetters,
        selectedWord
      );
      if (checkWinStatus === 'win') {
        // sendNotification('');
        setState({
          ...state,
          playable: false,
          msg: 'Congratulations, You Have Won!',
        });
      } else if (checkWinStatus === 'lose') {
        // sendNotification(`Game over. Correct word: ${selectedWord}`);
        setState({
          ...state,
          playable: false,
          msg: `You Lost. Correct Word: ${selectedWord}`,
        });
      }
    }

    const handleKeyDown = (event) => {
      const { key, keyCode } = event;

      if (keyCode >= 65 && keyCode <= 90) {
        const letter = key.toLowerCase();

        if (selectedWord.includes(letter)) {
          if (!correctLetters.includes(letter)) {
            setState({
              ...state,
              correctLetters: [...correctLetters, letter],
            });
          } else {
            sendNotification('You have already entered this letter');
          }
        } else {
          if (!wrongLetters.includes(letter)) {
            setState({
              ...state,
              wrongLetters: [...wrongLetters, letter],
            });
          } else {
            sendNotification('You have already entered this letter');
          }
        }
      }
    };

    window.addEventListener('keydown', handleKeyDown);

    // Clean up so we dont have lots of eventListenner
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [selectedWord, correctLetters, wrongLetters]);

  return (
    <div className="container text-center mt-5">
      <ToastContainer
        position="bottom-center"
        autoClose={2000}
        hideProgressBar={false}
        newestOnTop={false}
        closeOnClick
        rtl={false}
        pauseOnFocusLoss
        draggable
        pauseOnHover={false}
      />
      <WordInput />
      <EndGameModal />
      <div className="row m-5">
        <div className="col-sm-6 mb-5">
          <Figure />
        </div>
        <div className="col-sm-6 mb-5">
          <WrongLetters />
        </div>
      </div>
    </div>
  );
};

export default Index;

// JavaScript/hangman-vuejs/src/components/Index.vue
<template>
  <div class="vh-100 mt-5">
    <WordInput />
    <EndGameModal />
    <div class="row mt-5 text-center">
      <div class="col-sm-6 mb-5">
        <Figure />
      </div>
      <div class="col-sm-6 mb-5">
        <WrongLetters />
      </div>
    </div>
  </div>
</template>

<script>
import Vue from 'vue';
import Toasted from 'vue-toasted';

import { mapGetters, mapActions } from 'vuex';
import { checkWin } from '../helpers/helpers';

// Components
import Figure from './Figure';
import WordInput from './WordInput';
import WrongLetters from './WrongLetters';
import EndGameModal from './EndGameModal';

Vue.use(Toasted, {
  theme: 'outline',
  position: 'bottom-center',
  duration: 1000,
  singleton: true,
});

export default {
  name: 'Index',

  components: {
    Figure,
    WordInput,
    WrongLetters,
    EndGameModal,
  },

  methods: {
    ...mapActions([
      'addCorrectLetter',
      'addWrongLetter',
      'changeMsg',
      'changePlayable',
    ]),
    handleKeyPressed(e) {
      const { key, keyCode } = e;

      if (keyCode >= 65 && keyCode <= 90 && this.playable) {
        const letter = key.toLowerCase();

        if (this.selectedWord.includes(letter)) {
          if (!this.correctLetters.includes(letter)) {
            this.addCorrectLetter(letter);
          } else {
            this.$toasted.show('You have already entered this letter');
          }
        } else {
          if (!this.wrongLetters.includes(letter)) {
            this.addWrongLetter(letter);
          } else {
            this.$toasted.show('You have already entered this letter');
          }
        }
      }
    },
    handleStateChange(newValue, oldValue) {
      if (this.playable & (newValue !== oldValue)) {
        const checkWinStatus = checkWin(
          this.correctLetters,
          this.wrongLetters,
          this.selectedWord
        );

        if (checkWinStatus === 'win') {
          this.changeMsg('Congratulations, You Have Won!');
          this.changePlayable(false);
        } else if (checkWinStatus === 'lose') {
          this.changeMsg(`You Lost. Correct Word: ${this.selectedWord}`);
          this.changePlayable(false);
        }
      }
    },
  },

  watch: {
    correctLetters(newValue, oldValue) {
      this.handleStateChange(newValue, oldValue);
    },
    wrongLetters(newValue, oldValue) {
      this.handleStateChange(newValue, oldValue);
    },
  },

  created() {
    document.onkeydown = this.handleKeyPressed;
  },

  computed: {
    ...mapGetters({
      selectedWord: 'getSelectedWord',
      correctLetters: 'getCorrectLetters',
      wrongLetters: 'getWrongLetters',
      playable: 'getPlayable',
      msg: 'getMsg',
    }),
  },
};
</script>

<style scoped></style>
