// JavaScript/hangman-react/src/components/WordInput.js
import React, { useContext } from 'react';
import { Context } from '../context';
import randomWords from 'random-words';

const WordInput = () => {
  const [state, setState] = useContext(Context);
  const { selectedWord, correctLetters } = state;

  const changeWord = () => {
    setState({
      selectedWord: randomWords(),
      wrongLetters: [],
      correctLetters: [],
      playable: true,
      msg: null,
    });
  };

  if (selectedWord) {
    return (
      <>
        <h3>Enter The Hidden Word</h3>
        <div className="d-flex justify-content-center">
          {selectedWord.split('').map((letter, i) => {
            return (
              <span key={i} className="letter">
                {correctLetters.includes(letter) ? letter : ''}
              </span>
            );
          })}
        </div>
        <button className="btn btn-secondary my-3" onClick={changeWord}>
          Change The Word
        </button>
      </>
    );
  } else {
    return (
      <>
        <h3>Enter The Hidden Word</h3>
        <h6>Hidden word is loading...</h6>
      </>
    );
  }
};

export default WordInput;

// JavaScript/hangman-vuejs/src/components/WordInput.vue
<template>
  <div class="text-center">
    <h3>Enter The Hidden Word</h3>
    <div class="d-flex justify-content-center">
      <div v-for="(letter, i) in selectedWord.split('')" :key="i">
        <span class="letter" v-if="correctLetters.includes(letter)">{{
          letter
        }}</span>
        <span class="letter" v-else>{{ ' ' }}</span>
      </div>
    </div>
    <button @click="changeWord" class="btn btn-secondary my-3">
      Change The Word
    </button>
  </div>
</template>

<script>
import { mapGetters, mapActions } from 'vuex';

export default {
  name: 'WordInput',

  methods: {
    ...mapActions(['resetState']),
    changeWord() {
      this.resetState();
    },
  },

  computed: {
    ...mapGetters({
      selectedWord: 'getSelectedWord',
      correctLetters: 'getCorrectLetters',
    }),
  },
};
</script>

<style></style>
