// JavaScript/hangman-vuejs/src/components/layout/Navbar.vue
<template>
  <div class="bg-dark">
    <div class="container text-center">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <span class="navbar-brand mx-auto">Hangman - Find The Hidden Word</span>
      </nav>
    </div>
  </div>
</template>

<script>
export default {
  name: 'Navbar',
};
</script>

// JavaScript/hangman-react/src/components/layout/Navbar.js
import React from 'react';

const Navbar = () => {
  return (
    <div style={{ backgroundColor: '#343a40' }}>
      <div className="container">
        <nav className="navbar navbar-expand-lg navbar-dark bg-dark">
          <h3 className="navbar-brand mx-auto">
            Hangman - Find the Hidden Word
          </h3>
        </nav>
      </div>
    </div>
  );
};

export default Navbar;
