// JavaScript/hangman-react/src/components/layout/Footer.js
import React from 'react';

function Footer() {
  return (
    <footer className="page-footer font-small text-light bg-dark">
      <div className="container text-center">
        <div className="row">
          <div className="col-md-12 py-3">
            <div className="flex-center">
              <a
                href="https://www.facebook.com/mohammadreza.amini.33"
                rel="noopener noreferrer"
                target="_blank"
                className="fb-ic"
              >
                <i className="fab fa-facebook-f fa-lg white-text mr-md-5 mr-3 fa-2x">
                  {' '}
                </i>
              </a>
              <a
                href="https://www.instagram.com/mohammadreza99a/"
                rel="noopener noreferrer"
                target="_blank"
                className="ins-ic"
              >
                <i className="fab fa-instagram fa-lg white-text mr-md-5 mr-3 fa-2x">
                  {' '}
                </i>
              </a>
              <a
                href="https://github.com/Mohammadreza99A"
                target="_blank"
                rel="noopener noreferrer"
                className="github-ic"
              >
                <i className="fab fa-github fa-lg white-text fa-2x"> </i>
              </a>
            </div>
          </div>
        </div>
      </div>

      <div className="footer-copyright text-center py-3">
        © 2020 Copyright : Mohammadreza Amini
      </div>
    </footer>
  );
}

export default Footer;

// JavaScript/hangman-vuejs/src/components/layout/Footer.vue
<template>
  <footer class="page-footer font-small text-light bg-dark">
    <div class="container text-center">
      <div class="row">
        <div class="col-md-12 py-3">
          <div class="flex-center">
            <a
              href="https://www.facebook.com/mohammadreza.amini.33"
              rel="noopener noreferrer"
              target="_blank"
              class="fb-ic"
            >
              <i class="fab fa-facebook-f fa-lg white-text mr-md-5 mr-3 fa-2x">
              </i>
            </a>
            <a
              href="https://www.instagram.com/mohammadreza99a/"
              rel="noopener noreferrer"
              target="_blank"
              class="ins-ic"
            >
              <i class="fab fa-instagram fa-lg white-text mr-md-5 mr-3 fa-2x">
              </i>
            </a>
            <a
              href="https://github.com/Mohammadreza99A"
              target="_blank"
              rel="noopener noreferrer"
              class="github-ic"
            >
              <i class="fab fa-github fa-lg white-text fa-2x"> </i>
            </a>
          </div>
        </div>
      </div>
    </div>

    <div class="footer-copyright text-center py-3">
      © 2020 Copyright : Mohammadreza Amini
    </div>
  </footer>
</template>

<script>
export default {};
</script>

<style></style>
